{% set name = "spec2nii" %}
{% set version = "0.8.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 53b2af29f148ee027c557ca9c46a80b0d9607260dcb4ec0207a425332f080ec3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - spec2nii = spec2nii.spec2nii:main

requirements:
  build:
    - python >=3.9
    - pip
    - versioneer
    - pyyaml
  host:
    - python {{ python_min }}
    - pip
    - pyyaml
    - versioneer
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.26
    - nibabel
    - pydicom
    - pymapvbvd >=0.6.0
    - scipy >=1.13
    - brukerapi >=0.1.8
    - pandas
    - nifti-mrs >=1.3.2

test:
  requires:
    - python {{ python_min }}
  imports:
    - spec2nii
  commands:
    - spec2nii --help

about:
  home: https://github.com/wexeee/spec2nii
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Multi-format in vivo MR spectroscopy conversion to NIfTI
  description: |
    A program for multi-format in vivo MR spectroscopy conversion to NIFTI.
  doc_url: https://github.com/wexeee/spec2nii
  dev_url: https://github.com/wexeee/spec2nii

extra:
  recipe-maintainers:
    - wtclarke
