{% set name = "spec2nii" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9e84c69ec80c49432dcba3a69d54da162271cf88fe5edd52329b4fbb4459740d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - spec2nii = spec2nii.spec2nii:main

requirements:
  build:
    - python >=3.7
    - pip
    - versioneer
    - pyyaml
  host:
    - python >=3.7
    - pip
    - pyyaml
    - versioneer
  run:
    - python >=3.7
    - numpy
    - nibabel
    - pydicom
    - pymapvbvd >=0.5.2
    - scipy
    - brukerapi >=0.1.8
    - pandas
    - nifti-mrs >=0.1.3

test:
  imports:
    - spec2nii
  commands:
    - spec2nii --help

about:
  home: https://github.com/wexeee/spec2nii
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Multi-format in vivo MR spectroscopy conversion to NIfTI
  description: |
    A program for multi-format in vivo MR spectroscopy conversion to NIFTI.
  doc_url: https://github.com/wexeee/spec2nii
  dev_url: https://github.com/wexeee/spec2nii

extra:
  recipe-maintainers:
    - wtclarke
