{% set name = "spec2nii" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f7ffde5076a3fe07ff6bf735abd0fd26bc4f4412df0bd06cfed622d1faf27d15

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - spec2nii = spec2nii.spec2nii:main

requirements:
  host:
    - python >=3.7
    - pip
    - pyyaml
  run:
    - python >=3.7
    - numpy
    - nibabel
    - pydicom
    - pymapvbvd
    - scipy
    - brukerapi >=0.1.4.0
    - pandas

test:
  imports:
    - spec2nii
  commands:
    - spec2nii --help

about:
  home: https://github.com/wexeee/spec2nii
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Multi-format in vivo MR spectroscopy conversion to NIfTI
  description: |
    A program for multi-format in vivo MR spectroscopy conversion to NIFTI.
  doc_url: https://github.com/wexeee/spec2nii
  dev_url: https://github.com/wexeee/spec2nii

extra:
  recipe-maintainers:
    - wtclarke
